"""empty message

Revision ID: 5f152c6722b2
Revises: 60dde128317f
Create Date: 2022-04-08 15:42:45.196935

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f152c6722b2'
down_revision = '60dde128317f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.drop_constraint('fk_question_question_id_question', type_='foreignkey')
        batch_op.drop_column('question_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('question_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_question_question_id_question', 'question', ['question_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###
