"""empty message

Revision ID: 60dde128317f
Revises: aa327c530326
Create Date: 2022-04-08 15:41:13.144320

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60dde128317f'
down_revision = 'aa327c530326'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('question_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_question_question_id_question'), 'question', ['question_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_question_question_id_question'), type_='foreignkey')
        batch_op.drop_column('question_id')

    # ### end Alembic commands ###
